apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-changed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: "/unknown"
              port: 443
          ports:
            - containerPort: 80
